paths:
  uploads: uploads
  data: _data
  layouts: _layouts
  includes: _includes

collections_config:
  data:
    path: _data
    output: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    output: true
    filter: strict
  services:
    path: _services
    output: true
  testimonials:
    path: _testimonials
    output: false
    create:
      path: '[relative_base_path]/{author}.md'

collections_config_override: false

_inputs:
  logo-image:
    hidden: true
    cascade: true
  copy:
    type: textarea
    cascade: true
  title:
    hidden: true
    cascade: true
  layout:
    hidden: true
    cascade: true

timezone: US/Eastern